### ISSUE TITLE
[sshd] systemd support

### ISSUE THREAD

**Issue by halo** [funkensturm/warehouse#19]
Newer ubuntus don't have upstart. It's as simple as removing [this line](https://github.com/funkensturm/warehouse/blob/83e1305d1ea875f658274984469fd2981b69600b/cookbooks/system/sshd/recipes/config.rb#L15) but then it only works for systemd and not upstart any more. Maybe [this](https://github.com/dev-sec/chef-ssh-hardening/blob/2e7a89392bb654a8819c0c5ca80e6ca54fee6bec/recipes/server.rb#L29-L38)?

**Comment by fsmanuel** [comment]
solved by #24
